### PR TITLE
Fixing low-voltage flashing on STM32F7 parts.

### PR DESCRIPTION
**Pull request by zulusw**
Added stm32f7.s and stm32f7lv.s (the sooner was already supported but probably the definition of loader_code_stm32f7  in flash_loader.c was just winged from the F4 version by manually adding the opcode for the "dsb").

Instead of copy & paste the voltage detection code, I refactored it into a function. If that is not cool, let me know and I can revert that part.

Also, I haven't got a chance to test it out on an M4 yet. Will do over the weekend.

### CODE REVIEW

**Comment by xor-gate** [comment]
Looks good, If you verify and let me know it works on M4 we are good to go!

**Comment by xor-gate** [comment]
Checked already on m4 ?

**Comment by zulusw** [comment]
Jerry,

Here it is. (Tested both regular voltage and low voltage)
Below is the low voltage log.

Regards,
Andrea.

2017-03-14T10:48:11 INFO stlink/src/common.c: Loading device parameters....
2017-03-14T10:48:11 INFO stlink/src/common.c: Device connected is: F42x and
F43x device, id 0x20016419
2017-03-14T10:48:11 INFO stlink/src/common.c: SRAM size: 0x40000 bytes (256
KiB), Flash: 0x200000 bytes (2048 KiB) in pages of 16384 bytes
2017-03-14T10:48:11 INFO stlink/src/gdbserver/gdb-server.c: Chip ID is
00000419, Core ID is  2ba01477.
2017-03-14T10:48:11 INFO stlink/src/gdbserver/gdb-server.c: Listening at
*:4242...
2017-03-14T10:48:19 INFO stlink/src/gdbserver/gdb-server.c: Found 6 hw
breakpoint registers
2017-03-14T10:48:19 INFO stlink/src/gdbserver/gdb-server.c: GDB connected.
2017-03-14T10:48:23 INFO stlink/src/common.c: Attempting to write 16384
(0x4000) bytes to stm32 address: 134217728 (0x8000000)
Flash page at addr: 0x08000000 erased
2017-03-14T10:48:24 INFO stlink/src/common.c: Finished erasing 1 pages of
16384 (0x4000) bytes
2017-03-14T10:48:24 INFO stlink/src/common.c: Starting Flash write for
F2/F4/L4
2017-03-14T10:48:24 INFO stlink/src/flash_loader.c: Successfully loaded
flash loader in sram
Target voltage (2600 mV) too low for 32-bit flash, using 8-bit flash writes
size: 16384
2017-03-14T10:48:24 INFO stlink/src/common.c: Starting verification of
write complete
2017-03-14T10:48:25 INFO stlink/src/common.c: Flash written and verified!
jolly good!
2017-03-14T10:48:25 INFO stlink/src/common.c: Attempting to write 16384
(0x4000) bytes to stm32 address: 134234112 (0x8004000)
Flash page at addr: 0x08004000 erased
2017-03-14T10:48:25 INFO stlink/src/common.c: Finished erasing 1 pages of
16384 (0x4000) bytes
2017-03-14T10:48:25 INFO stlink/src/common.c: Starting Flash write for
F2/F4/L4
2017-03-14T10:48:25 INFO stlink/src/flash_loader.c: Successfully loaded
flash loader in sram
Target voltage (2600 mV) too low for 32-bit flash, using 8-bit flash writes
size: 16384
2017-03-14T10:48:26 INFO stlink/src/common.c: Starting verification of
write complete
2017-03-14T10:48:26 INFO stlink/src/common.c: Flash written and verified!
jolly good!
2017-03-14T10:48:26 INFO stlink/src/common.c: Attempting to write 16384
(0x4000) bytes to stm32 address: 134250496 (0x8008000)
Flash page at addr: 0x08008000 erased
2017-03-14T10:48:26 INFO stlink/src/common.c: Finished erasing 1 pages of
16384 (0x4000) bytes
2017-03-14T10:48:26 INFO stlink/src/common.c: Starting Flash write for
F2/F4/L4
2017-03-14T10:48:26 INFO stlink/src/flash_loader.c: Successfully loaded
flash loader in sram
Target voltage (2600 mV) too low for 32-bit flash, using 8-bit flash writes
size: 16384
2017-03-14T10:48:27 INFO stlink/src/common.c: Starting verification of
write complete
2017-03-14T10:48:27 INFO stlink/src/common.c: Flash written and verified!
jolly good!

**Comment by xor-gate** [comment]
Great, thanks for the improvement!

**Pull request merged**
