### PR TITLE
fix-482

### PR DESCRIPTION
**Pull request by OsterlaD**
Implement install delegate and use it in debian/rules.

Install of udev rules and modprobe config is still done in debian/rules.

### CODE REVIEW

**Comment by xor-gate** [comment]
The top level makefile should have for the install_* targets a dependency to debug/release:
When people directly type make install_debug it will fail. Also we should wrap a `install` target to `install_release`.

```
install_release: release 
...
install_debug: debug
...
```

**Comment by nekromant** [comment]
@xor-gate: It looks addition of the top-level Makefile breaks automated debian, I've fixed. Please don't yet merge @OsterlaD's fix, I have a cleaner solution on the way.

**Comment by OsterlaD** [comment]
Removed debian fixes.
But install delegate and documentation adaption may apply anyway.

**Comment by xor-gate** [comment]
So this can be closed in favor of PR #485 ?

**Comment by OsterlaD** [comment]
I think the install delegates would be useful anyway.
If you do not need them, just close the pull request.

Hopefully he gets its changes stable, it would be a clean solution.

**Comment by xor-gate** [comment]
I will close this, as soon as the stuff from @nekromant has been fixed/merged. I will add install delegates to the top level makefile. Thank you for you contribution!

**Comment by Nightwalker-87** [comment]
Closed in favour of #485.

**Pull request closed without merging**
