### PR TITLE
Added LIB_INSTALL_DIR to correct libs install on 64-bit systems

### PR DESCRIPTION
**Pull request by Vascom**
Solve for #633

### CODE REVIEW

**Comment by xor-gate** [comment]
This looks good, but it should autoselect lib and lib64. We probably need to implement the solution which is on the cmake mailinglist here: https://cmake.org/pipermail/cmake/2013-July/055374.html

**Comment by Vascom** [comment]
This not shoud autodetect lib and lib64. It set by external parameter:
`cmake .. -DLIB_INSTALL_DIR:PATH=/usr/lib64`

**Comment by xor-gate** [comment]
That is not true autodetection, that is passed by the developer which builds the package. CMake should be able to autodetect it if the default libdir is lib64. I'm not against adding build parameters but the idea would be good by default.

**Comment by Vascom** [comment]
Fedora has /usr/lib and /usr/lib64 simultaneously and you can't autodetect where I want place builded libs. Let maintainer do it via -DLIB_INSTALL_DIR:PATH= .

**Comment by xor-gate** [comment]
Yeah the lib contains 32 bit stuff which can run with the 32bit compatibility layer. But the default detected path should be lib64 because the system booted an amd64 or arm64 kernel anyway.

**Comment by Vascom** [comment]
You can add autodetect if you with but keep force redefinition of it by this parameter.

**Comment by xor-gate** [comment]
Yes that would be fine, but please document the addition of the this supported build parameter in [doc/compiling.doc](https://github.com/texane/stlink/blob/master/doc/compiling.md)

**Comment by Vascom** [comment]
This is enough?

**Comment by xor-gate** [comment]
Great, thanks for this. The name LIB_INSTALL_DIR comes from autoconf GNU projects, but I can live with this as it is convenient for everybody.

**Comment by Vascom** [comment]
Thanks.
I don't know whereit from but it used in %cmake macro for building Fedora packages:
```
  /usr/bin/cmake \
        -DCMAKE_C_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_CXX_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_Fortran_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
        -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
        -DSYSCONF_INSTALL_DIR:PATH=/etc \
        -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
%if "lib64" == "lib64" 
        -DLIB_SUFFIX=64 \
%endif 
        -DBUILD_SHARED_LIBS:BOOL=ON
```

**Comment by xor-gate** [comment]
It also adds the `-DLIB_SUFFIX=64` build parameter which seems it uses the solution from the CMake mailing list. The LIB_SUFFIX is probably not supported currently in stlink. I think still we need to implement the solution from the mailing list as I see the fedora specfile to build the RPM as it uses the "lib64" conditional and no /usr/lib64 is hardcoded.

**Comment by Vascom** [comment]
But -DLIB_SUFFIX is the same external parameter as -DLIB_INSTALL_DIR.

**Pull request merged**
