### PR TITLE
Unhexify GDB monitor commands (qRcmd)

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**
It improves readability and will allow parsing of more complex monitor
commands.

### CODE REVIEW

**Comment by texane** [comment]
Thanks for the pull. I spotted at least one error in your code, could you
fix it
and pull again ?

You allocate char cmd[cmd_len];
but you access the cmd_len + 1 item with cmd[cmd_len] = 0;

You should thus allocate at least cmd_len + 1 item.

Also, prefer static allocations when using the stack. Otherwise,
use malloc.

Thanks

2016-08-09 16:35 GMT+02:00 Fabien Chouteau <notifications@github.com>:

**Comment by xor-gate** [comment]
You should prefer `size_t` over `int` with sizes since C99. A other implementation which implements a gdb server is the blackmagic probe which can be used as a reference:

https://github.com/blacksphere/blackmagic/blob/master/src/hex_utils.c
https://github.com/blacksphere/blackmagic/blob/master/src/gdb_main.c
https://github.com/blacksphere/blackmagic/blob/master/src/gdb_packet.c

**Comment by Fabien-Chouteau** [comment]
I'm not sure if this is the standard workflow but I updated the commit. (git commit --amend && git push -f)

**Comment by xor-gate** [comment]
Yeah it is nice to have just one commit per fix/pull request. This is the same as rebase-squash (`git rebase -i master`)

**Comment by texane** [comment]
Merged, thanks. But I would suggest, for total correctness, checking outside the unhexify() for loop that sscanf access:
in[2 * i + 0]
in[2 * i + 1]
is always valid, which may not be the case. Rare conditions (in odd size + cross page allocation), but does not cost much.

**Comment by Fabien-Chouteau** [comment]
We can check if strlen(params) is a multiple of 2, which it should be.

I don't see how cross page allocation can be a problem.

**Comment by texane** [comment]
'it should be' ?  What about buggy clients ? Do not suppose, esp. if the check comes for free. Truncate the size if not a 2 multiple.
Cross page -> sscanf invalid read access even on a single invalid byte may cause a crash, depending on the next page access rights.

**Comment by Fabien-Chouteau** [comment]
I know it can happen, that's why I said 'it should be' not 'it will always be'. Note that the integer division (size_t alloc_size = (hex_len / 2) + 1;) will handle the case where strlen(params) is odd.

**Pull request merged**
