### PR TITLE
Add creation of icons for .desktop file

### PR DESCRIPTION
**Pull request by joede**
The GUI doesn't provide the icons needed to work with the `.desktop` file. See  #684! With this PR, I've added a script to create the necessary `hicolor` icons from the given `SVG` file.

I'm no CMake user, so I don't know how to add the `.desktop` and the icons to `CMakelist.txt`. After the installation is added to the `CMakelist.txt`, the `debian/stlink-gui.install` must be patched too.

**This is still needed:**
* copy `stlink.desktop` as `stlink-gui.desktp` to `/usr/share/applications/` (`${CMAKE_INSTALL_DATADIR}/applications/`?)
* copy `stlink-gui.xpm`  to `/usr/share/pixmaps/`
* copy `hicolor/*` to `/usr/share/icons/hicolor/`
* copy `stlink-gui_icon.svg` to `/usr/share/icons/hicolor/scalable/stlink-gui.svg`

### CODE REVIEW

**Comment by xor-gate** [comment]
Maybe @Vascom can help you out with this?

**Comment by Vascom** [comment]
As I found it is enough have only svg file.

**Comment by joede** [comment]
@xor-gate I can try it within the next days. I expect that GNOME should work with this, but I can't say which other desktops needs images. So I *only can test the icon usage with GNOME3*!

**Comment by joede** [comment]
OK, the icon is visible in GNOME3.

I've updated to PR to install the .desktop and the SVG icon with the Debian package. Therefore I have renamed the two files to `stlink-gui.*` which is IMO better. I have removed the installation instructions from the main `CMakeList.txt` to the `CMakeList.txt` of the stlink-gui one. Now all GUI related action is inside this file and no longer spread over two files.

*Again:* I don't know if the images are necessary for other desktops! Not all desktops use SVG...

**Comment by Vascom** [comment]
I suggest leaving only SVG and keeping track of bug reports.

**Comment by xor-gate** [comment]
@Vascom agreed

**Comment by xor-gate** [comment]
Thanks @joede for your contribution.

**Pull request merged**
