### PR TITLE
implement IHEX for the GUI

### PR DESCRIPTION
**Pull request by dev26th**
#713 The GUI interpreted all files as binaries. Try to load '*.hex' as Intel-HEX

### CODE REVIEW

**Comment by xor-gate** [comment]
Looks good @dev26th ! @FoxyHawk could you verify it works with this patch for you?

**Comment by FoxyHawk** [comment]
The reader part of the GUI work fine now.

update_file_reader

But the programme use all the file, not only the data.
update_post_prog

**Comment by FoxyHawk** [comment]
Tested with my file, everything is fine ^^

**Comment by xor-gate** [comment]
Thanks all!

**Pull request merged**
