### PR TITLE
Improved support for STM32G0xx series parts to fix Issue #850

### PR DESCRIPTION
**Pull request by mrfirmware**
- For Issue #850 
- Now properly distinguish between the smaller and larger variants
- Added support for the smaller variants, 'G030, 'G031, and 'G041
- Now flashes and debugs STM32G031K8 MCU

### CODE REVIEW

**Comment by gdamjan** [comment]
Tested this on a stm32g0316-disco board with the stm32g031j6 mcu. works fine.

**Comment by Nightwalker-87** [comment]
Duplicate of #825 which serves this request. Included in develop branch with commit 7c0ebda0b514fb4c707205259ab221bd90f4cf78.

**Comment by Nightwalker-87** [comment]
Merged to develop branch with commit 7c0ebda0b514fb4c707205259ab221bd90f4cf78.

**Comment by Nightwalker-87** [comment]
See also issues #825, #850, #856.

**Comment by Nightwalker-87** [comment]
Closes #825, #850 and #856.

**Comment by Nightwalker-87** [comment]
@mrfirmware: Thx for your contribution!

**Pull request merged**
