### PR TITLE
Add Man pages

### PR DESCRIPTION
**Pull request by alx741**
This is the first attempt to add man pages for the utilities (#208)

Only the man page for `st-util` is ready, if this is useful I will make the pages for the other binaries as well.

The Cmake rules are modified so doing `sudo make install` installs the man pages. Then doing `man st-util` works just fine.

The makrdown man pages need to be generated first by doing `make` in the `doc/man` directory. Maybe integrate this in the Cmake rules (?)

### CODE REVIEW

**Comment by texane** [comment]
Merged it but some modifications done. More work needed here, cf. following
commits logs.


2016-09-15 5:20 GMT+02:00 Daniel Campoverde <notifications@github.com>:

**Comment by xor-gate** [comment]
@alx741  looking good, we can continue discussion in #208 if you want. I will do some work before v1.3.0 release to integrate with cmake.

**Comment by alx741** [comment]
@xor-gate sure, I'll work on The other pages today

**Comment by Nightwalker-87** [comment]
See also PR #467.

**Pull request merged**
