### PR TITLE
Deprecate autotools and fix versioning, build with MinGW

### PR DESCRIPTION
**Pull request by xor-gate**
Now CMake loads the version from TRAVIS_TAG, git describe --always or local .version.
Implementation of discussion in #431, for `v.2.0.0`

@texane what do you think? Could you review-merge?

### CODE REVIEW

**Comment by texane** [comment]
Does it still compile on Windows with Mingw32 ? Does not look so
to me (ie. doc/mingw.md). I agree to remove autotools, but all the
currently supported systems must work and the corresponding
doc be up to date.

Appart from that, looks fine to me.

2016-06-18 16:24 GMT+02:00 Jerry Jacobs <notifications@github.com>:

**Comment by texane** [comment]
OK. We will wait for the merge then. Thanks for your work !

2016-06-18 16:37 GMT+02:00 Jerry Jacobs <notifications@github.com>:

**Comment by xor-gate** [comment]
With appveyor with some time and effort we can build visual studio and mingw builds under windows systems. But for now I will stick with only mingw because I have seen `#include <unistd.h>` which is totaly not native windows.

**Comment by xor-gate** [comment]
It almost works, but I have forgotten i need libusb -_-":
https://ci.appveyor.com/project/xor-gate/stlink/build/job/t0roxh150had32im

**Comment by xor-gate** [comment]
Finaly it eats libusb, but there are people who did break the tooling to build at windows completely:

https://ci.appveyor.com/project/xor-gate/stlink/build/7/job/8kmopkqgxmxhlham#L197
```
[ 56%] Linking C executable st-flash.exe
libstlink.a(common.c.obj): In function `map_file':
c:/projects/stlink/src/common.c:957: undefined reference to `mmap'
libstlink.a(common.c.obj): In function `unmap_file':
c:/projects/stlink/src/common.c:975: undefined reference to `munmap'
collect2.exe: error: ld returned 1 exit status
```

**Comment by xor-gate** [comment]
@texane, it took me more time then expected to integrate with AppVeyor `MSYS Makefile` generator project. I have it now building for 32 and 64 bit systems. I still need to update the documentation. What do you think?

Important: I would like you to activate AppVeyor integration for `texane/stlink` with the config file pointing to custom path: `.appveyor.yml`. Would you like to do this. For me it would be better to move stlink project into a separate organisation so the integrations don't impact your own account and you don't need to configure (sometimes complex) continues integration/continues deployment. 

The Pro of having a separate organisation would also be when in the upcoming time I will push binary releases from Travis CI and AppVeyor CI into github/bintray we need to have deployment keys which need to configured. Also for my own stlink continues integration setup I would like to add extra code coverage output (so we know most targets, and all flash loader variants work).

Thank you for your time.
Let me know how we can continue to extent and ease the first-time users and existing users.

**Comment by texane** [comment]
Hi,

regarding the Windows support, let me know when the documentation is
updated and we will merge. Thanks for that !

It is good to  add some support for continuous integration, but I do not
want
it to drive important decisions such as changing the project organization,
or
put constraints on the maintainers personal accounts.

2016-06-19 9:04 GMT+02:00 Jerry Jacobs <notifications@github.com>:

**Comment by xor-gate** [comment]
@texane I have updated the build instructions and added a build helper for windows. Now we only need a MinGW64 gcc toolchain without MSYS. I have tested this myself and it compiles and runs. For some reason there are some issues with device-claim under windows (but that is a different question to fix):

```
C:\Users\Jerry\Downloads\stlink-deprecate_autotools\build>st-info.exe --serial
libusb: error [init_device] device '\\.\USB#VID_0483&PID_374B&MI_02#6&2E55A1F8&0&0002' is no longer connected!
303636454646343835353530373535

C:\Users\Jerry\Downloads\stlink-deprecate_autotools\build>st-info.exe --descr
libusb: error [init_device] device '\\.\USB#VID_0483&PID_374B&MI_02#6&2E55A1F8&0&0002' is no longer connected!
L4 device

C:\Users\Jerry\Downloads\stlink-deprecate_autotools\build>st-info.exe --flash
libusb: error [init_device] device '\\.\USB#VID_0483&PID_374B&MI_02#6&2E55A1F8&0&0002' is no longer connected!
0xzx

C:\Users\Jerry\Downloads\stlink-deprecate_autotools\build>st-info.exe --sram
libusb: error [init_device] device '\\.\USB#VID_0483&PID_374B&MI_02#6&2E55A1F8&0&0002' is no longer connected!
0xzx

C:\Users\Jerry\Downloads\stlink-deprecate_autotools\build>st-info.exe --probe
Found zu stlink programmers
```

**Comment by texane** [comment]
Thanks !

2016-06-20 17:01 GMT+02:00 Jerry Jacobs <notifications@github.com>:

**Comment by xor-gate** [comment]
I have seen working AppVeyor and Travis with the `stlink/stlink`, so when this is happen to be merged and everything is in place you may disable integration for your account. Keep in mind, that no pull requests are build then.

**Comment by texane** [comment]
I will, thanks

2016-06-20 20:25 GMT+02:00 Jerry Jacobs <notifications@github.com>:

**Comment by xor-gate** [comment]
Some days have passed, another contributor updated the CMake files in PR #444 but first this should be merged. Then PR #444 could rebased on this.

**Comment by texane** [comment]
I will be on vacations for the next 2 weeks. Will take a look when coming
back.

2016-07-13 21:14 GMT+02:00 Jerry Jacobs <notifications@github.com>:

**Comment by xor-gate** [comment]
As discussed some time ago, we will be moving away from autotools. As people get confused and makes issue solving problematic. If there are any questions with cmake or the build system, don't hesitate to open a issue new issue for further discussion.

**Comment by texane** [comment]
Hi Jerry,

could we take this discussion back ?

As I understand, there are 3 topics to be discussed:

. Moving away from autotools: seems OK to me, but still has
to build on all the platforms currently supported, without loss
of quality as regard with what is currently provided.

. Windows support: still has to work. Can't we just take the
currently generated MSYS Makefile and live with them ? We
do not often change these, do not have to be generated at
every pull request.

. Adding a third party service to ease the Windows build: it
does not seem justified to me, esp. regarding the impact it
has on the project or owner accounts, as discussed earlier.
So my answer to this point is definitely no.

I hope we will make some progress,


2016-08-03 20:15 GMT+02:00 Jerry Jacobs <notifications@github.com>:

**Comment by xor-gate** [comment]
I will comment on the following points:

1. No quality is lost, it is even enforced on multiple platforms (Linux, MinGW, Mac OS). By using multiple compilers and environments.
2. The windows build is working with CMake and I have put a few hour effort to make it compile again. Generating static build files and putting it aside cmake is double and will confuse people again. We are unable with static build files to compile to multiple targets: Debug (debug symbols and coverage, Release (stripped from cruft for easier distribution).
3. I understand, but how can you guarantee "quality/working" as mentioned in point 1 without continues integration?

**Comment by texane** [comment]
2016-08-04 9:09 GMT+02:00 Jerry Jacobs <notifications@github.com>:

> I will comment on the following points:
>
>    1. No quality is lost, it is even enforced on multiple platforms
>    (Linux, MinGW, Mac OS). By using multiple compilers and environments.
>
>
OK


>
>    1. The windows build is working with CMake and I have put a few hour
>    effort to make it compile again. Generating static build files and putting
>    it aside cmake is double and will confuse people again. We are unable with
>    static build files to compile to multiple targets: Debug (debug symbols and
>    coverage, Release (stripped from cruft for easier distribution).
>
>
Just to understand: building on Windows works fine with CMake. If that is
so,
we can drop autotools then ...


>
>    1. I understand, but how can you guarantee "quality/working" as
>    mentioned in point 1 without continues integration?
>
>
As we did in the past: if the build fails on a platform, users will report
it. We
have the same problem to functionally test that a pull request wont break a
target, and it works fine.

**Pull request merged**
