### PR TITLE
Build debian package with more use of cmake

### PR DESCRIPTION
**Pull request by OsterlaD**
* Make use of `dh --buildsystem cmake`, as suggested by nekromant.
* Keep install rules of module config and udev rules separate, to keep normal cmake install as documented.
* Move libstlink.so symlink to dev-package, provided by nekromant.

### CODE REVIEW

**Comment by xor-gate** [comment]
Will this replace the work of #485?

**Comment by OsterlaD** [comment]
Well, this would be my solution without changes to cmake.
If you decide that it is better to change cmake behavior, then reject this pull request.
Currently it is documented to copy module config and udev rules by hand.
If you want to change this behavior #485 is to prefer.
If you want to keep this behavior then this pull request is to prefer.

**Comment by xor-gate** [comment]
I understand your concern about not touching cmake for the debian packaging. But I prefer fixing cmake for all platforms and debian packaging "at the same time". My decision is to get PR #485 ready and you can ask @nekromant if there are things you would like to see fixed if there are some thing in this PR which are not in the other.

**Comment by Nightwalker-87** [comment]
Closed in favour of #485.

**Pull request closed without merging**
