### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by mcoquelin-stm32**
Dear Texane,

This pull-request contains some preliminary reworks to have complete error propagation from libusb to st-flash tool.

I also changed some loaders to "commonize" their handling.

Please let me know what you thinkabout it.
Thanks in advance,
Maxime

### CODE REVIEW

**Comment by texane** [comment]
Hi,

thanks for the work, looks fine. However, it won't be merged it as is.

Until now, a single commit targets a specific feature / fix which makes
the code easy to revert in case of regression, an important aspect of
this tool given the number of supported platforms.

Thus, I encourage you to break the commit into individual pieces.

Cheers

2016-03-14 15:26 GMT+01:00 mcoquelin-stm32 <notifications@github.com>:

**Comment by mcoquelin-stm32** [comment]
Hi,

Thanks for the review.
Actually, that's what I did, this is split in 12 commits:
 	@mcoquelin-stm32 	read_debug32: Use a pointer instead of returning the value … 	bd27213
	@mcoquelin-stm32 	stlink_core_id: No need to return core_id value … 	5fcad7d
	@mcoquelin-stm32 	stlink_target_voltage: Check for libusb error … 	89c3b14
	@mcoquelin-stm32 	Make the backends propagate errors … 	64a48c7
	@mcoquelin-stm32 	stlink-common: Make stlink API propagate backend errors … 	93e958f
	@mcoquelin-stm32 	st-flash: Improve error handling … 	a9f00bc
	@mcoquelin-stm32 	stlink-common: Introduce type of flash controller enum … 	abcd47f
	@mcoquelin-stm32 	stlink-common: Simplify run_flash_loader() … 	5693181
	@mcoquelin-stm32 	stlink-common: Update STM32L0 and STM32L1 loader ABI … 	907383d
	@mcoquelin-stm32 	stlink-common: Update STM32L0/1 loaders to return remaining count in r2 … 	e43a737
	@mcoquelin-stm32 	stlink-common: Fix STM32L4 loader write count to reflect 64bits granu… … 	d0458ee
	@mcoquelin-stm32 	stlink-common: Ensure flash type is properly declared in device params … 	faa19b5
Should it be split in more commits?

Thanks in advance,
Maxime

**Comment by mcoquelin-stm32** [comment]
Thanks!

**Comment by texane** [comment]
No, that is fine. Thanks

**Pull request merged**
