### PR TITLE
Debian packaging, CMake and README.md fixes

### PR DESCRIPTION
**Pull request by bluca**
See invididual commits for details. I am preparing to upload stlink to Debian, and these are some changes required to pass the new package review process.

Fixes https://github.com/texane/stlink/issues/682

### CODE REVIEW

**Comment by bluca** [comment]
@xor-gate ping

**Comment by bluca** [comment]
Thanks!

**Comment by xor-gate** [comment]
Thank you for your effort!

**Comment by zoobab** [comment]
stlink package is pending here, no idea when it will be the archive: https://ftp-master.debian.org/new/stlink_1.5.0+ds-1.html

**Comment by bluca** [comment]
stlink-tools and stlink-gui are now available in Debian unstable, testing and stretch-backports, and Ubuntu 18.10

**Comment by joede** [comment]
great, thanks @bluca

**Comment by zoobab** [comment]
I made a PR to change the README.md https://github.com/texane/stlink/pull/821

**Pull request merged**
