### PR TITLE
Make udev rules and modprobe conf installation optional

### PR DESCRIPTION
**Pull request by g-arjones**

### CODE REVIEW

**Comment by g-arjones** [comment]
Ping? @texane @xor-gate @karlp

**Comment by xor-gate** [comment]
It seems you have broken the build for all platforms with cmake ~v3.0: https://travis-ci.org/texane/stlink/jobs/443197492#L1021

**Comment by g-arjones** [comment]
It seems like this was happening before my patch: https://travis-ci.org/texane/stlink/jobs/428338176#L1014

See build history for more occurrences.. 

Problem is in this line:

https://github.com/texane/stlink/blob/7fafee24a57c4cfa24df56383546d5c04866b512/CMakeLists.txt#L121

Which is unrelated to changes I introduced.. or am I missing something?

**Comment by xor-gate** [comment]
Aah sorry for the delay, i was unaware some other change had broken the build. Thank you for the contribution.

**Pull request merged**
