### PR TITLE
packaging: Improvements to debian package build.

### PR DESCRIPTION
**Pull request by OsterlaD**
Solution to problems with debian package build issue.

### CODE REVIEW

**Comment by xor-gate** [comment]
You should not rely on the `build/Debug/doc/man/*.1` because this only used during building debug targets. Debian package should use only Release targets and fetch the pre-generated man-pages from `doc/man/*.1`.

**Comment by xor-gate** [comment]
See here: https://github.com/texane/stlink/blob/cmake-fixes/doc/man/CMakeLists.txt#L9

**Comment by xor-gate** [comment]
I have merged `cmake-fixes` into `master`, you may rebase to `master` which builds again. Travis building broke for some unknown reason and I have hardened the cmake version detection now.

**Comment by OsterlaD** [comment]
Reworked patch stack on master.
Now manpages contains doc/man/st-.1 entry, corresponding to install entry usr/bin/st-.
The debian/copyright file indicates BSD-3-clause license with copyright holders from LICENSE file.

**Comment by OsterlaD** [comment]
Added udev rules and modprobe installation rules.

**Comment by xor-gate** [comment]
Could you squash-merge all your commits into one? Then we are ready to go!

**Comment by OsterlaD** [comment]
There are still some issues.
* manpages expect to install from source, not build direcotry or debian/tmp, but the nice man pages are created from *.md files and were placed under build/Debug/doc/man
* stlink-gui requires src/tools/gui/stlink-gui.ui file and seems to expect it under /usr/local/share/stlink
* is it correct to build debug variant?

**Comment by xor-gate** [comment]
I will comment inline:
> * manpages expect to install from source, not build direcotry or debian/tmp, but the nice man pages are created from *.md files and were placed under build/Debug/doc/man

Package maintainers should only use the generated manpages from `doc/man/*.1`  texane has put the missing generated roff files there in latest master. This takes away the pandoc dependency for package maintainers.

> * stlink-gui requires src/tools/gui/stlink-gui.ui file and seems to expect it under /usr/local/share/stlink

This is hardcoded into the GUI currently and it has not fixed yet.

> * is it correct to build debug variant?

The Debug target is not what you want in a package, because it contains debug symbols (GDB) and is not optimized (-O0).

**Comment by Nightwalker-87** [comment]
Closed in favour of #484.

**Comment by Nightwalker-87** [comment]
Closed in favour of #484.

**Pull request closed without merging**
