### PR TITLE
Fix const warning on struct stlink_chipid_params

### PR DESCRIPTION
**Pull request by jmlemetayer**
Just fix the 2 warnings:

    warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]

### CODE REVIEW

**Comment by xor-gate** [comment]
Thanks for fixing! I have overlooked this. And also have a related issue open (when compiling with CMake):
https://github.com/texane/stlink/issues/402

**Comment by jmlemetayer** [comment]
No problem. Thanks for your reactivity.

**Comment by xor-gate** [comment]
If you have time and would like to contribute some more maybe you can look into issue #402?

**Comment by jmlemetayer** [comment]
I will try to check this issue

**Comment by xor-gate** [comment]
Great, when you work on it, and need some discussion you should write at #402. Thanks!

**Pull request merged**
